apiVersion: v1
kind: ServiceAccount
metadata:
  name: snowball
  namespace: homer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    propagate.hnc.x-k8s.io/treeSelect: lisa
  name: observer
  namespace: homer
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    propagate.hnc.x-k8s.io/treeSelect: lisa
  name: observer
  namespace: homer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: observer
subjects:
  - kind: ServiceAccount
    name: snowball
    namespace: homer
