apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hnc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-hnc
  source:
    path: hnc/overlays/production
    repoURL: https://github.com/lanbingcloud/demo-hnc.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

